version: 2
jobs:
  test:
    docker:
      - image: wata727/tflint
    steps:
      - checkout
      - run:
          name: Lint Terraform for cluster
          command: |
            apk add bash
            /bin/bash ./.circleci/run_tflint.sh
          environment:
            WORKSPACE: datakube-dev
workflows:
  version: 2
  test:
    jobs:
      - test
